# Run as Administrator
# Packs and signs the NextcloudUWP ARM Release .appx from the .NET Native ilc output.
# The PFX is auto-generated by VS on the first successful build.

$projectDir = 'Z:\nextcloud-uwp\NextcloudUWP'
$ilcDir     = "$projectDir\bin\ARM\Release\ilc"
$winkits    = 'C:\Program Files (x86)\Windows Kits\10'
$makeappx   = "$winkits\bin\10.0.16299.0\x64\makeappx.exe"
$signtool   = "$winkits\bin\10.0.16299.0\x64\signtool.exe"
$pfxPath    = "$projectDir\NextcloudUWP_TemporaryKey.pfx"
$appxOut    = 'Z:\nextcloud-uwp\NextcloudUWP_ARM.appx'
$layout     = 'Z:\nextcloud-uwp\AppXLayoutARM'

# Validate prerequisites
if (-not (Test-Path $ilcDir))   { Write-Error "ilc dir not found: $ilcDir`nBuild Release|ARM first."; exit 1 }
if (-not (Test-Path $pfxPath))  { Write-Error "PFX not found: $pfxPath`nBuild the project once in VS to generate it."; exit 1 }
if (-not (Test-Path $makeappx)) { Write-Error "makeappx.exe not found at $makeappx"; exit 1 }

# Clean and create layout
if (Test-Path $layout) { Remove-Item $layout -Recurse -Force }
New-Item $layout               -ItemType Directory | Out-Null
New-Item "$layout\RuntimeDlls" -ItemType Directory | Out-Null
New-Item "$layout\Assets"      -ItemType Directory | Out-Null

Write-Host "Building ARM layout from ilc/..."

# Manifest — strip Debug VCLibs dependency + lower MinVersion for W10M (build 15254)
$manifest = Get-Content "$ilcDir\AppxManifest.xml" -Raw
$manifest = $manifest -replace '\s*<PackageDependency Name="Microsoft\.VCLibs\.140\.00\.Debug"[^/]*/>', ''
$manifest = $manifest -replace 'MinVersion="10\.0\.16299\.0"', 'MinVersion="10.0.15063.0"'
$manifest = $manifest -replace 'MaxVersionTested="10\.0\.16299\.0"', 'MaxVersionTested="10.0.15063.0"'
Set-Content "$layout\AppxManifest.xml" $manifest -Encoding UTF8

# App binaries
Copy-Item "$ilcDir\NextcloudUWP.exe"    "$layout\"
Copy-Item "$ilcDir\NextcloudUWP.dll"    "$layout\"
Copy-Item "$ilcDir\NextcloudUWP.xr.xml" "$layout\"
Copy-Item "$ilcDir\resources.pri"       "$layout\"
Copy-Item "$ilcDir\clrcompression.dll"  "$layout\"

# Native SQLite DLL (SQLite.Net-PCL ships sqlite3.dll; copy any .dll not already handled)
Get-ChildItem "$ilcDir\*.dll" |
    Where-Object { $_.Name -notin @('NextcloudUWP.dll','clrcompression.dll') } |
    Copy-Item -Destination "$layout\"

# Runtime DLLs — only present in some .NET Native versions
if (Test-Path "$ilcDir\RuntimeDlls") {
    Get-ChildItem "$ilcDir\RuntimeDlls\*.dll" | Copy-Item -Destination "$layout\RuntimeDlls\"
} else {
    Remove-Item "$layout\RuntimeDlls" -Force
}

# Assets (ilc output + StoreLogo.png from project source, which .NET Native doesn't copy)
Copy-Item "$ilcDir\Assets\*" "$layout\Assets\" -Recurse
if (-not (Test-Path "$layout\Assets\StoreLogo.png")) {
    Copy-Item "$projectDir\Assets\StoreLogo.png" "$layout\Assets\" -ErrorAction SilentlyContinue
}

Write-Host "Packing..."
& $makeappx pack /d $layout /p $appxOut /o
if ($LASTEXITCODE -ne 0) { Write-Error "MakeAppx failed"; exit 1 }

Write-Host "Signing..."
& $signtool sign /fd SHA256 /f $pfxPath /p DevOnly $appxOut
if ($LASTEXITCODE -ne 0) { Write-Error "SignTool failed"; exit 1 }

Write-Host "Done. APPX at: $appxOut"
